//! Shared agent utilities used by commands, relay, and telegram modules.

use crate::agent_session::ProcessProvider;
use crate::config::jobs::{Job, JobType, NotifyTarget, TelegramLogMode, TelegramNotify};
use crate::config::settings::AppSettings;

/// Returns the path to the agent working directory.
pub fn agent_dir_path() -> std::path::PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".config")
        .join("clawtab")
        .join("agent")
}

/// Generate the auto-generated context for the agent directory.
/// Contains workspace info, available tools, and Telegram communication instructions.
pub(crate) fn generate_agent_cwt_context(
    settings: &AppSettings,
    jobs: &[Job],
    chat_id: Option<i64>,
) -> String {
    let mut out = String::new();

    out.push_str("<!-- Auto-generated by ClawTab. Regenerated on agent start. -->\n");
    out.push_str("# ClawTab Telegram Agent\n\n");
    out.push_str("You are the ClawTab interactive agent. The user communicates with you through Telegram.\n\n");

    // Communication protocol -- this is the most important section
    out.push_str("## Communication Protocol\n\n");
    out.push_str("IMPORTANT: You MUST send ALL your responses and questions to the user via Telegram using curl.\n");
    out.push_str("The user cannot see your terminal output. Telegram is your ONLY communication channel.\n\n");

    let has_token = settings
        .telegram
        .as_ref()
        .map_or(false, |tg| !tg.bot_token.is_empty());
    let cid = chat_id.or_else(|| {
        settings
            .telegram
            .as_ref()
            .and_then(|tg| tg.chat_ids.first().copied())
    });

    if has_token {
        if let Some(cid) = cid {
            out.push_str("### Sending messages\n\n");
            out.push_str(
                "Send every response, question, status update, or result to Telegram:\n\n",
            );
            out.push_str("```bash\n");
            out.push_str(&format!(
                "curl -s -X POST \"https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{{\"chat_id\": {}, \"text\": \"Your message here\"}}'\n",
                cid
            ));
            out.push_str("```\n\n");

            out.push_str("### Receiving messages\n\n");
            out.push_str("The user's follow-up messages are typed into your terminal input automatically by ClawTab.\n");
            out.push_str("After sending a question or completing a task, simply wait -- the user's reply will appear as your next prompt input.\n\n");
        }
    }

    out.push_str("### Rules\n\n");
    out.push_str("- ALWAYS send your answers and questions via the Telegram curl command above.\n");
    out.push_str("- After completing a task or asking a question, wait for the next input.\n");
    out.push_str("- Do NOT terminate or exit unless the user explicitly asks you to.\n");
    out.push_str(
        "- Keep messages concise. For long output, summarize and offer to share details.\n",
    );
    out.push_str("- Only operate within the allowed directories listed below.\n");

    // Collect unique allowed directories from jobs
    let mut dirs: Vec<String> = Vec::new();
    for job in jobs {
        if let Some(ref fp) = job.folder_path {
            if !dirs.contains(fp) {
                dirs.push(fp.clone());
            }
        }
        if let Some(ref wd) = job.work_dir {
            if !dirs.contains(wd) {
                dirs.push(wd.clone());
            }
        }
    }
    if !settings.default_work_dir.is_empty() && !dirs.contains(&settings.default_work_dir) {
        dirs.push(settings.default_work_dir.clone());
    }

    out.push_str("\n## Allowed Directories\n\n");
    for d in &dirs {
        out.push_str(&format!("- `{}`\n", d));
    }

    if let Some(config_dir) = crate::config::config_dir() {
        out.push_str(&format!("- `{}` (ClawTab config)\n", config_dir.display()));
    }

    // Workspace listing
    if !jobs.is_empty() {
        out.push_str("\n## Configured Jobs\n\n");
        for job in jobs {
            let jt = match job.job_type {
                JobType::Binary => "bin",
                JobType::Claude => "claude",
                JobType::Job => "job",
            };
            let dir = job
                .folder_path
                .as_deref()
                .or(job.work_dir.as_deref())
                .unwrap_or("-");
            out.push_str(&format!("- `{}` [{}] dir: `{}`\n", job.name, jt, dir));
        }
    }

    out.push_str("\n## Job Management CLI\n\n");
    out.push_str("`cwtctl` is available for managing ClawTab jobs:\n\n");
    out.push_str("```\n");
    out.push_str("cwtctl ping           # Check if ClawTab daemon is running\n");
    out.push_str("cwtctl list           # List all configured jobs\n");
    out.push_str("cwtctl status         # Show status of all jobs\n");
    out.push_str("cwtctl run <name>     # Run a job immediately\n");
    out.push_str("cwtctl pause <name>   # Pause a running job\n");
    out.push_str("cwtctl resume <name>  # Resume a paused job\n");
    out.push_str("cwtctl restart <name> # Restart a job\n");
    out.push_str("```\n");

    out
}

/// Build a synthetic `Job` for running Claude as an ad-hoc interactive agent.
/// Writes enriched prompt to `~/.config/clawtab/agent/.agent-prompt.md`
/// and returns a Job that can be passed to `execute_job`.
///
/// When `target_dir` is provided, the agent runs in that directory instead of the
/// default agent dir. The job name/slug become `agent-<folder>` so multiple
/// per-folder agents can coexist.
pub fn build_agent_job(
    prompt: &str,
    chat_id: Option<i64>,
    settings: &AppSettings,
    jobs: &[Job],
    target_dir: Option<&str>,
    provider: Option<ProcessProvider>,
    model: Option<String>,
) -> Result<Job, String> {
    let agent_dir = agent_dir_path();
    std::fs::create_dir_all(&agent_dir)
        .map_err(|e| format!("Failed to create agent dir: {}", e))?;

    // For group/folder agents, skip the agent cwt.md - just run claude in that folder
    let enriched = if target_dir.is_some() {
        prompt.to_string()
    } else {
        // Regenerate the auto-generated context with the specific chat_id
        let context = generate_agent_cwt_context(settings, jobs, chat_id);
        let cwt_md_path = agent_dir.join("cwt.md");
        std::fs::write(&cwt_md_path, &context)
            .map_err(|e| format!("Failed to write agent cwt.md: {}", e))?;
        format!("@{}\n\n{}", cwt_md_path.display(), prompt)
    };

    // Derive name/slug and work_dir from target_dir
    let (job_id, job_slug, work_dir) = if let Some(dir) = target_dir {
        let project_dir = std::path::Path::new(dir);
        let folder = project_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("agent");
        let slug = format!("agent-{}", folder);
        (
            slug.clone(),
            slug,
            project_dir.to_string_lossy().to_string(),
        )
    } else {
        (
            "agent".to_string(),
            "agent".to_string(),
            agent_dir.display().to_string(),
        )
    };

    // Write prompt to a per-agent file to avoid collisions
    let prompt_filename = format!(".agent-prompt-{}.md", job_slug);
    let prompt_path = agent_dir.join(&prompt_filename);
    std::fs::write(&prompt_path, &enriched)
        .map_err(|e| format!("Failed to write agent prompt: {}", e))?;

    Ok(Job {
        name: job_id,
        job_type: JobType::Claude,
        enabled: true,
        path: prompt_path.display().to_string(),
        args: Vec::new(),
        cron: String::new(),
        secret_keys: Vec::new(),
        env: std::collections::HashMap::new(),
        work_dir: Some(work_dir),
        tmux_session: None,
        aerospace_workspace: None,
        folder_path: None,
        job_id: Some("default".to_string()),
        telegram_chat_id: chat_id,
        telegram_log_mode: TelegramLogMode::OnPrompt,
        telegram_notify: TelegramNotify::default(),
        notify_target: if chat_id.is_some() {
            NotifyTarget::Telegram
        } else {
            NotifyTarget::None
        },
        group: "agent".to_string(),
        slug: job_slug,
        skill_paths: Vec::new(),
        params: Vec::new(),
        kill_on_end: false,
        auto_yes: false,
        agent_provider: provider,
        agent_model: model,
        added_at: Some(chrono::Utc::now().to_rfc3339()),
    })
}
