import type { RemoteJob, JobStatus, RunRecord } from "@clawtab/shared";
import type { ClaudeQuestion } from "@clawtab/shared";

export const DEMO_JOBS: RemoteJob[] = [
  {
    name: "deploy-api",
    job_type: "binary",
    enabled: true,
    cron: "0 */6 * * *",
    group: "production",
    slug: "deploy-api",
    work_dir: "/srv/api",
  },
  {
    name: "claude-review-prs",
    job_type: "claude",
    enabled: true,
    cron: "*/30 * * * *",
    group: "production",
    slug: "claude-review-prs",
    work_dir: "~/workspace/app",
  },
  {
    name: "backup-db",
    job_type: "binary",
    enabled: true,
    cron: "0 2 * * *",
    group: "maintenance",
    slug: "backup-db",
    work_dir: "/srv/backups",
  },
  {
    name: "claude-refactor",
    job_type: "claude",
    enabled: true,
    cron: "",
    group: "development",
    slug: "claude-refactor",
    work_dir: "~/workspace/app",
  },
  {
    name: "lint-check",
    job_type: "binary",
    enabled: false,
    cron: "0 * * * *",
    group: "development",
    slug: "lint-check",
    work_dir: "~/workspace/app",
  },
  {
    name: "sync-assets",
    job_type: "binary",
    enabled: true,
    cron: "0 4 * * 1",
    group: "maintenance",
    slug: "sync-assets",
    work_dir: "/srv/cdn",
  },
];

const now = new Date();
const ago = (mins: number) => new Date(now.getTime() - mins * 60000).toISOString();

export const DEMO_STATUSES: Record<string, JobStatus> = {
  "deploy-api": { state: "success", last_run: ago(12) },
  "claude-review-prs": { state: "running", run_id: "demo-run-1", started_at: ago(3) },
  "backup-db": { state: "success", last_run: ago(120) },
  "claude-refactor": { state: "success", last_run: ago(60) },
  "lint-check": { state: "failed", last_run: ago(45), exit_code: 1 },
  "sync-assets": { state: "success", last_run: ago(1440) },
};

export const DEMO_QUESTIONS: ClaudeQuestion[] = [
  {
    pane_id: "demo-pane-1",
    cwd: "~/workspace/app",
    tmux_session: "demo",
    window_name: "claude",
    question_id: "demo-q-1",
    context_lines: "I'd like to refactor the authentication module to use OAuth2.\nThis will affect 12 files. Should I proceed?",
    options: [
      { number: "1", label: "Yes" },
      { number: "2", label: "No" },
    ],
    matched_job: "claude-review-prs",
    matched_group: "production",
  },
];

export const DEMO_LOGS: Record<string, string> = {
  "deploy-api": [
    "$ docker build -t api:latest .",
    "Step 1/8 : FROM node:20-alpine",
    " ---> 2a5b3c4d5e6f",
    "Step 2/8 : WORKDIR /app",
    " ---> Using cache",
    "Step 3/8 : COPY package*.json ./",
    " ---> Using cache",
    "Step 4/8 : RUN npm ci --production",
    " ---> Running in 8f9a0b1c2d3e",
    "added 847 packages in 12s",
    "Step 5/8 : COPY . .",
    "Step 6/8 : RUN npm run build",
    "> api@2.4.1 build",
    "> tsc && node scripts/bundle.js",
    "Build complete: dist/server.js (2.1 MB)",
    "Step 7/8 : EXPOSE 3000",
    "Step 8/8 : CMD [\"node\", \"dist/server.js\"]",
    "Successfully built a1b2c3d4e5f6",
    "Successfully tagged api:latest",
    "$ kubectl rollout restart deployment/api -n production",
    "deployment.apps/api restarted",
    "Waiting for rollout to finish: 1 old replicas pending...",
    "deployment \"api\" successfully rolled out",
  ].join("\n"),
  "claude-review-prs": [
    "Checking open pull requests...",
    "Found 3 open PRs to review:",
    "",
    "PR #142: feat: add OAuth2 support",
    "  Author: alice | Files changed: 12 | +847 -203",
    "  Reviewing...",
    "  - src/auth/oauth.ts: Looks good, proper token refresh handling",
    "  - src/middleware/auth.ts: Consider adding rate limiting to token endpoint",
    "  - tests/auth.test.ts: Good coverage, missing edge case for expired refresh tokens",
    "  Review posted with 2 suggestions",
    "",
    "PR #139: fix: memory leak in websocket handler",
    "  Author: bob | Files changed: 3 | +24 -8",
    "  Reviewing...",
    "  - src/ws/handler.ts: LGTM, proper cleanup on disconnect",
    "  Approved",
    "",
    "PR #137: chore: upgrade dependencies",
    "  Author: dependabot | Files changed: 2 | +312 -298",
    "  Reviewing...",
  ].join("\n"),
  "backup-db": [
    "Starting database backup...",
    "Connected to PostgreSQL 16.2",
    "Dumping schema: public",
    "  - users (124,847 rows)",
    "  - sessions (52,301 rows)",
    "  - jobs (1,203 rows)",
    "  - audit_log (892,445 rows)",
    "Compressing backup...",
    "backup-2026-03-19-0200.sql.gz (48.2 MB)",
    "Uploading to s3://backups/db/...",
    "Upload complete. Pruning backups older than 30 days...",
    "Removed 2 old backups.",
    "Backup completed successfully.",
  ].join("\n"),
  "claude-refactor": [
    "Analyzing codebase for refactoring opportunities...",
    "Scanning 48 files in src/",
    "",
    "Found 3 candidates:",
    "  1. src/services/payment.ts - Extract PaymentProcessor class (complexity: 42)",
    "  2. src/utils/validators.ts - Consolidate duplicate validation logic",
    "  3. src/api/routes.ts - Split into domain-specific route modules",
    "",
    "Starting with #1: src/services/payment.ts",
    "  Creating PaymentProcessor class...",
    "  Moving processPayment() -> PaymentProcessor.process()",
    "  Moving refundPayment() -> PaymentProcessor.refund()",
    "  Moving validateCard() -> PaymentProcessor.validateCard()",
    "  Updating 8 imports across the codebase",
    "  Running tests... 47/47 passed",
    "  Refactoring complete.",
  ].join("\n"),
  "lint-check": [
    "$ eslint src/ --ext .ts,.tsx",
    "",
    "src/utils/format.ts",
    "  14:5  error  'result' is assigned but never used  @typescript-eslint/no-unused-vars",
    "  28:1  error  Missing return type on function      @typescript-eslint/explicit-function-return-type",
    "",
    "src/components/Header.tsx",
    "  7:10  warning  'useState' is defined but never used  @typescript-eslint/no-unused-vars",
    "",
    "2 errors, 1 warning",
    "Exit code: 1",
  ].join("\n"),
  "sync-assets": [
    "Syncing assets from /srv/cdn to S3...",
    "aws s3 sync /srv/cdn s3://assets-cdn/ --delete",
    "upload: images/hero-v3.webp (240 KB)",
    "upload: fonts/inter-var.woff2 (98 KB)",
    "delete: images/hero-v2.webp",
    "Synced 147 files, uploaded 2, deleted 1.",
    "Invalidating CloudFront cache...",
    "Invalidation created: I3EXAMPLE",
    "Done.",
  ].join("\n"),
};

export const DEMO_RUNS: Record<string, RunRecord[]> = {
  "deploy-api": [{
    id: "demo-run-deploy-1",
    job_name: "deploy-api",
    started_at: ago(12),
    finished_at: ago(10),
    exit_code: 0,
    trigger: "cron",
    stdout: DEMO_LOGS["deploy-api"],
    stderr: "",
  }],
  "backup-db": [{
    id: "demo-run-backup-1",
    job_name: "backup-db",
    started_at: ago(120),
    finished_at: ago(118),
    exit_code: 0,
    trigger: "cron",
    stdout: DEMO_LOGS["backup-db"],
    stderr: "",
  }],
  "claude-refactor": [{
    id: "demo-run-refactor-1",
    job_name: "claude-refactor",
    started_at: ago(60),
    finished_at: ago(55),
    exit_code: 0,
    trigger: "manual",
    stdout: DEMO_LOGS["claude-refactor"],
    stderr: "",
  }],
  "lint-check": [{
    id: "demo-run-lint-1",
    job_name: "lint-check",
    started_at: ago(45),
    finished_at: ago(44),
    exit_code: 1,
    trigger: "cron",
    stdout: DEMO_LOGS["lint-check"],
    stderr: "",
  }],
  "sync-assets": [{
    id: "demo-run-sync-1",
    job_name: "sync-assets",
    started_at: ago(1440),
    finished_at: ago(1438),
    exit_code: 0,
    trigger: "cron",
    stdout: DEMO_LOGS["sync-assets"],
    stderr: "",
  }],
};

export function isDemoJob(jobName: string): boolean {
  return DEMO_JOBS.some((j) => j.name === jobName || j.slug === jobName);
}
