import type { RemoteJob, JobStatus, RunRecord, DetectedProcess } from "@clawtab/shared";
import type { ClaudeQuestion } from "@clawtab/shared";

export const DEMO_JOBS: RemoteJob[] = [
  {
    name: "deploy-api",
    job_type: "binary",
    enabled: true,
    cron: "0 */6 * * *",
    group: "production",
    slug: "deploy-api",
    work_dir: "/srv/api",
  },
  {
    name: "claude-review-prs",
    job_type: "claude",
    enabled: true,
    cron: "*/30 * * * *",
    group: "production",
    slug: "claude-review-prs",
    work_dir: "~/workspace/app",
    agent_provider: "claude",
  },
  {
    name: "backup-db",
    job_type: "binary",
    enabled: true,
    cron: "0 2 * * *",
    group: "maintenance",
    slug: "backup-db",
    work_dir: "/srv/backups",
  },
  {
    name: "claude-refactor",
    job_type: "claude",
    enabled: true,
    cron: "",
    group: "development",
    slug: "claude-refactor",
    work_dir: "~/workspace/app",
  },
  {
    name: "lint-check",
    job_type: "binary",
    enabled: false,
    cron: "0 * * * *",
    group: "development",
    slug: "lint-check",
    work_dir: "~/workspace/app",
  },
  {
    name: "sync-assets",
    job_type: "binary",
    enabled: true,
    cron: "0 4 * * 1",
    group: "maintenance",
    slug: "sync-assets",
    work_dir: "/srv/cdn",
  },
];

const now = new Date();
const ago = (mins: number) => new Date(now.getTime() - mins * 60000).toISOString();

export const DEMO_STATUSES: Record<string, JobStatus> = {
  "deploy-api": { state: "success", last_run: ago(12) },
  "claude-review-prs": { state: "success", last_run: ago(18) },
  "backup-db": { state: "success", last_run: ago(120) },
  "claude-refactor": { state: "success", last_run: ago(60) },
  "lint-check": { state: "failed", last_run: ago(45), exit_code: 1 },
  "sync-assets": { state: "success", last_run: ago(1440) },
};

export const DEMO_QUESTIONS: ClaudeQuestion[] = [
  {
    pane_id: "demo-pane-claude",
    cwd: "~/workspace/app",
    tmux_session: "demo",
    window_name: "claude",
    question_id: "demo-q-1",
    context_lines: "I'd like to refactor the authentication module to use OAuth2.\nThis will affect 12 files. Should I proceed?",
    options: [
      { number: "1", label: "Yes" },
      { number: "2", label: "No" },
    ],
    matched_group: "development",
  },
];

export const DEMO_LOGS: Record<string, string> = {
  "deploy-api": [
    "$ docker build -t api:latest .",
    "Step 1/8 : FROM node:20-alpine",
    " ---> 2a5b3c4d5e6f",
    "Step 2/8 : WORKDIR /app",
    " ---> Using cache",
    "Step 3/8 : COPY package*.json ./",
    " ---> Using cache",
    "Step 4/8 : RUN npm ci --production",
    " ---> Running in 8f9a0b1c2d3e",
    "added 847 packages in 12s",
    "Step 5/8 : COPY . .",
    "Step 6/8 : RUN npm run build",
    "> api@2.4.1 build",
    "> tsc && node scripts/bundle.js",
    "Build complete: dist/server.js (2.1 MB)",
    "Step 7/8 : EXPOSE 3000",
    "Step 8/8 : CMD [\"node\", \"dist/server.js\"]",
    "Successfully built a1b2c3d4e5f6",
    "Successfully tagged api:latest",
    "$ kubectl rollout restart deployment/api -n production",
    "deployment.apps/api restarted",
    "Waiting for rollout to finish: 1 old replicas pending...",
    "deployment \"api\" successfully rolled out",
  ].join("\n"),
  "claude-review-prs": [
    "Checking open pull requests...",
    "Found 3 open PRs to review:",
    "",
    "PR #142: feat: add OAuth2 support",
    "  Author: alice | Files changed: 12 | +847 -203",
    "  Reviewing...",
    "  - src/auth/oauth.ts: Looks good, proper token refresh handling",
    "  - src/middleware/auth.ts: Consider adding rate limiting to token endpoint",
    "  - tests/auth.test.ts: Good coverage, missing edge case for expired refresh tokens",
    "  Review posted with 2 suggestions",
    "",
    "PR #139: fix: memory leak in websocket handler",
    "  Author: bob | Files changed: 3 | +24 -8",
    "  Reviewing...",
    "  - src/ws/handler.ts: LGTM, proper cleanup on disconnect",
    "  Approved",
    "",
    "PR #137: chore: upgrade dependencies",
    "  Author: dependabot | Files changed: 2 | +312 -298",
    "  Reviewing...",
  ].join("\n"),
  "codex-investigate-flake": [
    "$ codex",
    "Codex ready in ~/workspace/app",
    "",
    "user",
    "Find the source of the flaky billing webhook test and propose the smallest fix.",
    "",
    "codex",
    "I will inspect the failing test, the webhook handler, and any shared clock helpers.",
    "",
    "$ rg -n \"billing webhook|webhook\" src tests",
    "tests/billing/webhook.test.ts:42:describe(\"billing webhook\", () => {",
    "src/billing/webhook.ts:18:export async function handleBillingWebhook(req) {",
    "",
    "$ pnpm test tests/billing/webhook.test.ts --runInBand",
    "FAIL tests/billing/webhook.test.ts",
    "  billing webhook",
    "    updates subscription period end",
    "",
    "Expected: 2026-06-01T00:00:00.000Z",
    "Received: 2026-05-31T17:00:00.000Z",
    "",
    "codex",
    "The test compares local midnight against a UTC timestamp. I am checking the date normalizer before changing the assertion.",
  ].join("\n"),
  "opencode-upgrade-ui": [
    "$ opencode",
    "OpenCode session started",
    "cwd: ~/workspace/clawtab",
    "",
    "user",
    "Tighten the mobile dashboard spacing and keep the terminal readable on narrow screens.",
    "",
    "opencode",
    "I will review the dashboard layout and the shared terminal sizing.",
    "",
    "$ rg -n \"ContentContainer|terminalFrame|ProcessCard\" public/remote",
    "public/remote/app/job/[name].tsx:251:        <View style={[styles.terminalFrame, ...",
    "public/remote/src/components/ProcessCard.tsx:44:  const logPreview = process.log_lines",
    "",
    "$ pnpm -s exec tsc --noEmit",
    "No type errors found.",
    "",
    "opencode",
    "The narrow layout is constrained by fixed terminal controls. I am reducing chrome before touching the terminal viewport.",
  ].join("\n"),
  "backup-db": [
    "Starting database backup...",
    "Connected to PostgreSQL 16.2",
    "Dumping schema: public",
    "  - users (124,847 rows)",
    "  - sessions (52,301 rows)",
    "  - jobs (1,203 rows)",
    "  - audit_log (892,445 rows)",
    "Compressing backup...",
    "backup-2026-03-19-0200.sql.gz (48.2 MB)",
    "Uploading to s3://backups/db/...",
    "Upload complete. Pruning backups older than 30 days...",
    "Removed 2 old backups.",
    "Backup completed successfully.",
  ].join("\n"),
  "claude-refactor": [
    "Analyzing codebase for refactoring opportunities...",
    "Scanning 48 files in src/",
    "",
    "Found 3 candidates:",
    "  1. src/services/payment.ts - Extract PaymentProcessor class (complexity: 42)",
    "  2. src/utils/validators.ts - Consolidate duplicate validation logic",
    "  3. src/api/routes.ts - Split into domain-specific route modules",
    "",
    "Starting with #1: src/services/payment.ts",
    "  Creating PaymentProcessor class...",
    "  Moving processPayment() -> PaymentProcessor.process()",
    "  Moving refundPayment() -> PaymentProcessor.refund()",
    "  Moving validateCard() -> PaymentProcessor.validateCard()",
    "  Updating 8 imports across the codebase",
    "  Running tests... 47/47 passed",
    "  Refactoring complete.",
  ].join("\n"),
  "lint-check": [
    "$ eslint src/ --ext .ts,.tsx",
    "",
    "src/utils/format.ts",
    "  14:5  error  'result' is assigned but never used  @typescript-eslint/no-unused-vars",
    "  28:1  error  Missing return type on function      @typescript-eslint/explicit-function-return-type",
    "",
    "src/components/Header.tsx",
    "  7:10  warning  'useState' is defined but never used  @typescript-eslint/no-unused-vars",
    "",
    "2 errors, 1 warning",
    "Exit code: 1",
  ].join("\n"),
  "sync-assets": [
    "Syncing assets from /srv/cdn to S3...",
    "aws s3 sync /srv/cdn s3://assets-cdn/ --delete",
    "upload: images/hero-v3.webp (240 KB)",
    "upload: fonts/inter-var.woff2 (98 KB)",
    "delete: images/hero-v2.webp",
    "Synced 147 files, uploaded 2, deleted 1.",
    "Invalidating CloudFront cache...",
    "Invalidation created: I3EXAMPLE",
    "Done.",
  ].join("\n"),
};

export const DEMO_RUNS: Record<string, RunRecord[]> = {
  "deploy-api": [{
    id: "demo-run-deploy-1",
    job_id: "deploy-api",
    started_at: ago(12),
    finished_at: ago(10),
    exit_code: 0,
    trigger: "cron",
    stdout: DEMO_LOGS["deploy-api"],
    stderr: "",
  }],
  "backup-db": [{
    id: "demo-run-backup-1",
    job_id: "backup-db",
    started_at: ago(120),
    finished_at: ago(118),
    exit_code: 0,
    trigger: "cron",
    stdout: DEMO_LOGS["backup-db"],
    stderr: "",
  }],
  "claude-refactor": [{
    id: "demo-run-refactor-1",
    job_id: "claude-refactor",
    started_at: ago(60),
    finished_at: ago(55),
    exit_code: 0,
    trigger: "manual",
    stdout: DEMO_LOGS["claude-refactor"],
    stderr: "",
  }],
  "lint-check": [{
    id: "demo-run-lint-1",
    job_id: "lint-check",
    started_at: ago(45),
    finished_at: ago(44),
    exit_code: 1,
    trigger: "cron",
    stdout: DEMO_LOGS["lint-check"],
    stderr: "",
  }],
  "sync-assets": [{
    id: "demo-run-sync-1",
    job_id: "sync-assets",
    started_at: ago(1440),
    finished_at: ago(1438),
    exit_code: 0,
    trigger: "cron",
    stdout: DEMO_LOGS["sync-assets"],
    stderr: "",
  }],
};

export const DEMO_TERMINALS: Record<string, string> = {
  "claude-review-prs": [
    "clawtab on main [!]",
    "➜ claude",
    " ▐▛███▜▌   Claude Code v2.1.159",
    "▝▜█████▛▘  Opus 4.8 with high effort · Claude Max",
    "  ▘▘ ▝▝    ~/workspace/tgs/clawtab",
    "",
    "────────────────────────────────────────────────────────────────────────────",
    "❯ Try \"create a util logging.py that...\"",
    "────────────────────────────────────────────────────────────────────────────",
    "  Opus 4.8",
    "  INSERT ← for agents",
    "",
    "› Implement {feature}",
  ].join("\n"),
  "codex-investigate-flake": [
    "    113 +          currentSend({",
    "    114 +            type: \"subscribe_pty\",",
    "    115 +            id: nextId(),",
    "    116 +            pane_id: paneId,",
    "    117 +            tmux_session: tmuxSession,",
    "    118 +            cols: dims.cols,",
    "    119 +            rows: dims.rows,",
    "    120 +          });",
    "    121 +          ptySubscriptions.set(paneId, { count: 1, tmuxSession });",
    "    122 +          subscribedRef.current = true;",
    "    123 +        }, 120);",
    "    124 +      }",
    "    125      }",
    "",
    "• Ran pnpm -s exec tsc --noEmit",
    "  └ (no output)",
    "",
    "────────────────────────────────────────────────────────────────────────────",
    "",
    "• TypeScript passes after the PTY hook change. I’ll reload the local Brave tab once more to make sure the app still renders against the real connected state.",
    "",
    "✔ You approved codex to run osascript <<'APPLESCRIPT' ... this time",
    "",
    "• Ran osascript <<'APPLESCRIPT'",
    "  │ tell application \"Brave Browser\"",
    "  │   tell window id 1279624201",
    "  │ … +12 lines",
    "  └ {\"url\":\"http://localhost:1942/?job=clawjobs%2Fdiscover-big-tech-pass-b\",\"title\":\"ClawTab\"}",
    "",
    "• Refactored the demo agents to use the real agent tab path instead of the fake terminal view.",
    "",
    "› If the shell content is not readable, it is garbled. Is it possible for you to get the content of the cloud code, codex and open code windows that I have open and then just use the content in the demo app as this content?",
  ].join("\n"),
  "opencode-upgrade-ui": [
    "clawtab",
    "➜",
    "",
    "                                                                ▄",
    "                               ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▄ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀",
    "                               ▀  ▀ ▀  ▀ ▀▀▀▀ ▀  ▀ ▀    ▀  ▀ ▀  ▀ ▀▀▀▀",
    "                               ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀",
    "",
    "",
    "             ┃",
    "             ┃  Ask anything... \"Fix a TODO in the codebase\"",
    "             ┃",
    "             ┃  Build · GLM-5.1 Z.AI Coding Plan",
    "             ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
    "                                                             tab agents  ctrl+p commands",
    "",
    "",
    "  ~/workspace/tgs/clawtab:main                                                              1.15.5",
  ].join("\n"),
};

export const DEMO_PTY_OUTPUT_BY_PANE: Record<string, string> = {
  "demo-pane-claude": DEMO_TERMINALS["claude-review-prs"],
  "demo-pane-codex": DEMO_TERMINALS["codex-investigate-flake"],
  "demo-pane-opencode": DEMO_TERMINALS["opencode-upgrade-ui"],
};

export const DEMO_PROCESSES: DetectedProcess[] = [
  {
    pane_id: "demo-pane-claude",
    cwd: "~/workspace/app",
    version: "demo",
    display_name: "Claude review",
    pane_title: "claude",
    provider: "claude",
    can_fork_session: false,
    can_send_skills: false,
    can_inject_secrets: false,
    tmux_session: "demo",
    window_name: "claude",
    matched_group: "development",
    matched_job: null,
    log_lines: DEMO_TERMINALS["claude-review-prs"],
    first_query: "Review open pull requests and flag anything risky before merge.",
    last_query: "I need approval before posting the review comment.",
    session_started_at: ago(3),
    token_count: 42300,
  },
  {
    pane_id: "demo-pane-codex",
    cwd: "~/workspace/app",
    version: "demo",
    display_name: "Codex flake investigation",
    pane_title: "codex",
    provider: "codex",
    can_fork_session: false,
    can_send_skills: false,
    can_inject_secrets: false,
    tmux_session: "demo",
    window_name: "codex",
    matched_group: "development",
    matched_job: null,
    log_lines: DEMO_TERMINALS["codex-investigate-flake"],
    first_query: "Find the source of the flaky billing webhook test and propose the smallest fix.",
    last_query: "The test compares local midnight against a UTC timestamp.",
    session_started_at: ago(7),
    token_count: 31800,
  },
  {
    pane_id: "demo-pane-opencode",
    cwd: "~/workspace/app",
    version: "demo",
    display_name: "OpenCode UI upgrade",
    pane_title: "opencode",
    provider: "opencode",
    can_fork_session: false,
    can_send_skills: false,
    can_inject_secrets: false,
    tmux_session: "demo",
    window_name: "opencode",
    matched_group: "development",
    matched_job: null,
    log_lines: DEMO_TERMINALS["opencode-upgrade-ui"],
    first_query: "Tighten the mobile dashboard spacing and keep the terminal readable on narrow screens.",
    last_query: "I am reducing chrome before touching the terminal viewport.",
    session_started_at: ago(11),
    token_count: 26700,
  },
];

export function isDemoJob(jobName: string): boolean {
  return DEMO_JOBS.some((j) => j.name === jobName || j.slug === jobName);
}
