import type { RemoteJob, JobStatus, JobSortMode } from "../../types/job";
import type { DetectedProcess, ShellPane } from "../../types/process";
import { processDisplayTitle, shortenPath } from "../../util/format";
import type { SidebarSelectableItem } from "./sign";

function getStatusTimestamp(status: JobStatus | undefined): string | null {
  if (!status) return null;
  if (status.state === "running") return status.started_at;
  if (status.state === "success") return status.last_run;
  if (status.state === "failed") return status.last_run;
  return null;
}

function bestTimestamp(jobs: RemoteJob[], statuses: Record<string, JobStatus>): string | null {
  let best: string | null = null;
  for (const job of jobs) {
    const timestamp = getStatusTimestamp(statuses[job.slug]);
    if (timestamp && (!best || timestamp > best)) best = timestamp;
  }
  return best;
}

function newestAdded(jobs: RemoteJob[]): string | null {
  let best: string | null = null;
  for (const job of jobs) {
    const timestamp = job.added_at;
    if (timestamp && (!best || timestamp > best)) best = timestamp;
  }
  return best;
}

export function sortGroupKeys(
  keys: string[],
  grouped: Map<string, RemoteJob[]>,
  mode: JobSortMode,
  statuses: Record<string, JobStatus>,
): string[] {
  const sorted = [...keys];
  if (mode === "name") {
    sorted.sort((a, b) => {
      const displayA = a === "default" ? "General" : a;
      const displayB = b === "default" ? "General" : b;
      return displayA.localeCompare(displayB);
    });
  } else if (mode === "recent") {
    sorted.sort((a, b) => {
      const bestA = bestTimestamp(grouped.get(a) ?? [], statuses);
      const bestB = bestTimestamp(grouped.get(b) ?? [], statuses);
      if (bestA && bestB) return bestB.localeCompare(bestA);
      if (bestA) return -1;
      if (bestB) return 1;
      return a.localeCompare(b);
    });
  } else if (mode === "added") {
    sorted.sort((a, b) => {
      const bestA = newestAdded(grouped.get(a) ?? []);
      const bestB = newestAdded(grouped.get(b) ?? []);
      if (bestA && bestB) return bestB.localeCompare(bestA);
      if (bestA) return -1;
      if (bestB) return 1;
      return a.localeCompare(b);
    });
  }
  return sorted;
}

function normalizeSearchText(value: string | null | undefined): string {
  return (value ?? "").toLowerCase();
}

export function matchesQuery(values: Array<string | null | undefined>, query: string): boolean {
  return values.some((value) => normalizeSearchText(value).includes(query));
}

export function displayGroupName(group: string, jobs: RemoteJob[]): string {
  if (group !== "default") return group;
  const folderPath = jobs[0]?.folder_path ?? jobs[0]?.work_dir;
  return folderPath ? folderPath.split("/").filter(Boolean).pop() ?? "General" : "General";
}

export function matchesProcessQuery(process: DetectedProcess, query: string): boolean {
  return matchesQuery([
    processDisplayTitle(process),
    process.display_name,
    process.pane_title,
    process.first_query,
    process.last_query,
    process.cwd,
    shortenPath(process.cwd),
    process.provider,
  ], query);
}

export function matchesShellQuery(shell: ShellPane, query: string): boolean {
  const displayName = shell.display_name ?? shell.pane_title ?? shortenPath(shell.cwd);
  return matchesQuery([
    displayName,
    shell.display_name,
    shell.pane_title,
    shell.cwd,
    shortenPath(shell.cwd),
    "shell",
  ], query);
}

function extractGeneratedJobName(text: string | null | undefined): string | null {
  if (!text || !text.includes("Auto-generated by ClawTab")) return null;
  const backtickMatch = text.match(/Job name:\s*`([^`]+)`/i);
  if (backtickMatch?.[1]) return backtickMatch[1].trim();
  const lineMatch = text.match(/Job name:\s*([^\n\r]+)/i);
  return lineMatch?.[1]?.trim() ?? null;
}

export function inferProcessJobSlug(
  process: DetectedProcess,
  jobs: RemoteJob[],
  statuses: Record<string, JobStatus>,
): string | null {
  const knownJob = process.matched_job
    ? jobs.find((job) => job.slug === process.matched_job)
    : null;
  if (knownJob) return knownJob.slug;

  for (const job of jobs) {
    const status = statuses[job.slug];
    if (status?.state === "running" && status.pane_id === process.pane_id) {
      return job.slug;
    }
  }

  const generatedName =
    extractGeneratedJobName(process.first_query)
    ?? extractGeneratedJobName(process.log_lines)
    ?? extractGeneratedJobName(process.last_query);
  if (!generatedName) return null;

  const generatedNameLower = generatedName.toLowerCase();
  const candidates = jobs.filter((job) => (
    (job.group || "default") === (process.matched_group || "default")
    && (job.name.toLowerCase() === generatedNameLower || job.slug.toLowerCase() === generatedNameLower)
  ));
  return candidates[0]?.slug ?? null;
}

export function areSelectableItemsEqual(
  left: SidebarSelectableItem[],
  right: SidebarSelectableItem[],
): boolean {
  if (left.length !== right.length) return false;
  for (let index = 0; index < left.length; index += 1) {
    if (left[index].kind !== right[index].kind || left[index].key !== right[index].key) {
      return false;
    }
  }
  return true;
}
