import { Platform, StyleSheet } from "react-native";

import { colors } from "../../theme/colors";
import { spacing } from "../../theme/spacing";

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  list: {
    padding: spacing.lg,
  },
  nativeGroupedRows: {
    marginHorizontal: spacing.md,
    marginVertical: spacing.md,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: colors.groupedSurface,
  },
  webGroupedRows: {
    marginHorizontal: spacing.xs,
    marginVertical: spacing.md,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: colors.groupedSurface,
  },
  nativeGroupHeaderWrap: {
    marginHorizontal: spacing.md,
  },
  jobWithPaneToggle: {
    position: "relative",
  },
  jobPaneToggle: {
    position: "absolute",
    top: spacing.xs,
    left: spacing.xs,
    zIndex: 5,
    width: 22,
    height: 22,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  jobPaneToggleText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontFamily: "monospace",
  },
  jobChildProcesses: {
    marginTop: spacing.xs,
    marginLeft: spacing.lg,
    paddingLeft: spacing.sm,
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
  },
  jobChildProcess: {
    opacity: 0.96,
  },
  empty: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
    gap: spacing.sm,
  },
  emptyTitle: { color: colors.text, fontSize: 18, fontWeight: "600" },
  emptyText: { color: colors.textSecondary, fontSize: 14 },
  groupHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  groupHeaderTitleArea: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  groupHeaderSegmentSlot: {
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  groupHeaderMenuSlot: {
    flexShrink: 0,
    alignItems: "flex-end",
  },
  groupAgentFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  groupAgentFooterPath: {
    flex: 1,
    textAlign: "right",
  },
  groupFooter: {
    alignItems: "flex-end",
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  activeWorkspaceGroup: {
    backgroundColor: colors.accentBg,
    marginLeft: -spacing.lg,
    marginRight: -spacing.lg,
    paddingLeft: spacing.lg,
    paddingRight: spacing.lg,
    paddingTop: spacing.sm / 2,
    paddingBottom: spacing.sm / 2,
    borderRadius: 8,
    boxShadow: "inset 1px 1px 0 rgba(255,255,255,0.08), inset -1px -1px 0 rgba(0,0,0,0.12)",
  },
  activeWorkspaceHeaderRow: {
    backgroundColor: "transparent",
    borderRadius: 6,
  },
  activeWorkspaceHeaderText: {
    color: colors.accent,
  },
  groupHeaderArrowBtn: {
    paddingHorizontal: 2,
    paddingVertical: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  addJobBtn: {
    width: Platform.OS === "web" ? 28 : 34,
    height: Platform.OS === "web" ? 28 : 34,
    borderRadius: Platform.OS === "web" ? 14 : 17,
    marginLeft: "auto",
    backgroundColor: colors.groupedSurface,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  addJobBtnDots: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  addJobBtnDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.textSecondary,
  },
  groupHeaderArrow: { fontFamily: "monospace", fontSize: 10, color: colors.textSecondary },
  groupHeader: {
    color: colors.textSecondary,
    fontSize: Platform.OS === "web" ? 13 : 15,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
    flexShrink: 1,
  },
  groupFolderPath: {
    color: colors.textMuted,
    fontSize: 12,
    flexShrink: 1,
    minWidth: 0,
  },
  searchIcon: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 140,
    gap: 6,
    backgroundColor: colors.surface,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  searchInput: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    paddingVertical: 4,
    outlineStyle: "none",
  } as any,
  searchClear: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "500",
    paddingHorizontal: 4,
  },
  sortRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: spacing.xs,
    rowGap: spacing.xs,
    marginBottom: spacing.xs,
    zIndex: 10,
  },
  nativeGroupSegmentRow: {
    marginLeft: spacing.xs,
  },
  nativeToolbarRow: {
    paddingHorizontal: spacing.md,
  },
  nativeGlobalTabsSegment: {
    marginBottom: spacing.lg,
  },
  sortControl: {
    marginLeft: "auto",
  },
  sortTrigger: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  sortTriggerText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "500",
  },
  sortTriggerArrow: {
    color: colors.textSecondary,
    fontSize: 10,
  },
});
