import { StyleSheet, Platform } from "react-native";
import { colors } from "../../theme/colors";
import { radius, spacing } from "../../theme/spacing";

const isWeb = Platform.OS === "web";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
    ...(isWeb ? { borderRadius: radius.lg, overflow: "hidden" as const } : {}),
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  content: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    zIndex: 200,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    zIndex: 200,
  },
  backButton: {
    width: 28,
    height: 28,
    minWidth: 28,
    maxWidth: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
  },
  backArrow: {
    color: colors.textSecondary,
    fontSize: 18,
    lineHeight: 22,
  },
  jobName: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "600",
    flexShrink: 1,
  },
  titleEditBtn: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  titleEditText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  pathRow: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  pathText: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: "monospace",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    rowGap: spacing.sm,
    flexWrap: "nowrap",
    zIndex: 200,
    ...(isWeb ? { position: "relative" as const } : {}),
  },
  runtimeText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontFamily: "monospace",
  },
  headerPathText: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: "monospace",
    flex: 1,
    minWidth: 0,
  },
  queryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  queryLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
    width: 42,
    flexShrink: 0,
  },
  queryLine: {
    color: colors.textSecondary,
    fontSize: 12,
    flex: 1,
    minWidth: 0,
  },
  queryLineDim: {
    color: colors.textMuted,
    fontSize: 12,
    flex: 1,
    minWidth: 0,
  },
  tokenCount: {
    fontSize: 11,
    fontFamily: "monospace",
    fontWeight: "700",
    flexShrink: 0,
  },
  runtimeDim: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: "monospace",
  },
  headerTitleText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
    maxWidth: 220,
    flexShrink: 1,
  },
  infoPills: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    flexWrap: "nowrap",
    flexShrink: 0,
  },
  infoPill: {
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
  },
  infoLeadingIcon: {
    minWidth: 28,
    minHeight: 28,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "visible",
  },
  infoProviderBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoPillIcon: {
    paddingHorizontal: 6,
    minWidth: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  compactInfoLetter: {
    lineHeight: 11,
    letterSpacing: 0,
    textAlign: "center",
  },
  infoLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "600",
  },
  cronText: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: "monospace",
  },
  nextRunText: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    flexWrap: "nowrap",
    flexShrink: 1,
    minWidth: 0,
    overflow: "hidden",
  },
  actionBtn: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.sm,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  actionBtnCompact: {
    paddingHorizontal: spacing.md,
    paddingVertical: 2,
  },
  actionBtnSquare: {
    width: 24,
    height: 24,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  actionText: {
    fontSize: 14,
    fontWeight: "600",
  },
  actionTextCompact: {
    fontSize: 12,
  },
  runTriangle: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderTopWidth: 5,
    borderBottomWidth: 5,
    borderLeftColor: "#fff",
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    marginLeft: 2,
  },
  runTriangleMuted: {
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    borderLeftColor: colors.accent,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    marginLeft: 1,
  },
  section: {
    gap: spacing.sm,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  sectionTitle: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  collapseArrow: {
    fontFamily: "monospace",
    fontSize: 9,
    color: colors.textSecondary,
  },
  expandOutputHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  logsContainer: {
    overflow: "hidden" as any,
    position: "relative" as any,
    width: "100%" as any,
  },
  questionContext: {
    backgroundColor: "#111",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    maxHeight: 140,
  },
  questionContextText: {
    fontFamily: "monospace",
    fontSize: 11,
    lineHeight: 16,
    color: colors.textSecondary,
  },
  runsContainer: {
    gap: 1,
  },
  runsEmpty: {
    color: colors.textMuted,
    fontSize: 12,
    paddingVertical: spacing.sm,
  },
  runRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    marginBottom: 2,
  },
  runRowExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  runLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  runInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  runStatus: {
    fontSize: 12,
    fontWeight: "500",
  },
  runTrigger: {
    fontSize: 12,
    color: colors.textMuted,
  },
  runRight: {
    alignItems: "flex-end",
  },
  runTime: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  runExpandBtn: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg,
  },
  runExpandIcon: {
    fontSize: 12,
    color: colors.textSecondary,
    fontFamily: "monospace",
  },
  runPaneLink: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg,
  },
  runPaneLinkText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  runDuration: {
    fontSize: 11,
    color: colors.textMuted,
  },
  optionBar: {
    flexGrow: 0,
    flexShrink: 0,
    borderTopWidth: 1,
    borderTopColor: "#303033",
    backgroundColor: "#1c1c1e",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.32,
    shadowRadius: 16,
    elevation: 12,
  },
  optionAnswerScroll: {
    flexGrow: 0,
    flexShrink: 0,
    width: "100%",
  },
  optionBarContent: {
    flexDirection: "row",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    alignItems: "center",
  },
  optionBtn: {
    minHeight: 46,
    minWidth: 0,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentBg,
  },
  optionBtnText: {
    color: colors.accent,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
    textAlign: "center",
  },
  autoYesRow: {
    flexGrow: 0,
    flexShrink: 0,
    marginTop: spacing.sm,
    width: "100%",
  },
  autoYesRowContent: {
    flexDirection: "row",
    flexGrow: 1,
    width: "100%",
    paddingHorizontal: spacing.md,
    alignItems: "center",
  },
  autoYesBtn: {
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.warning,
  },
  autoYesBtnActive: {
    backgroundColor: colors.warningBg,
  },
  autoYesBtnText: {
    color: colors.warning,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  runRightRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  zoomBtn: {
    padding: 6,
  },
  zoomOverlay: {
    position: "absolute",
    top: 8,
    right: 10,
    width: 28,
    height: 28,
    borderRadius: 4,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  zoomIcon: {
    color: colors.textMuted,
    fontSize: 18,
    fontFamily: "monospace",
  },
  runLogs: {
    padding: spacing.sm,
    backgroundColor: "#000",
    borderRadius: radius.sm,
    marginTop: 4,
    marginBottom: 2,
    gap: spacing.sm,
  },
  runTerminalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  runTerminalMeta: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  runTerminalTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
  },
  runTerminalPath: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: "monospace",
  },
  runTerminalActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  runTerminalBody: {
    height: 320,
    overflow: "hidden" as any,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  liveRunZoomOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(0,0,0,0.45)",
    padding: spacing.lg,
    zIndex: 500,
  },
  liveRunZoomCard: {
    flex: 1,
    minHeight: 0,
    backgroundColor: colors.bg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden" as const,
  },
  liveRunZoomPath: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: "monospace",
    maxWidth: 240,
  },
  liveRunZoomTerminal: {
    flex: 1,
    minHeight: 0,
    backgroundColor: "#000",
  },
  runLogsText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontFamily: "monospace",
    lineHeight: 16,
  },
  activeRunMarker: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  zoomModal: {
    flex: 1,
    backgroundColor: "#000",
  },
  zoomHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  zoomHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  zoomHeaderLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "600",
  },
  zoomHeaderTime: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  zoomHeaderDuration: {
    color: colors.textMuted,
    fontSize: 11,
  },
  zoomCloseBtn: {
    padding: spacing.sm,
  },
  zoomCloseText: {
    color: colors.textSecondary,
    fontSize: 18,
  },
  zoomLogScroll: {
    flex: 1,
  },
  zoomLogContent: {
    padding: spacing.md,
  },
  zoomLogText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: "monospace",
    lineHeight: 18,
  },
  moreBtn: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  moreBtnText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 12,
  },
});
